In [1]:
#for HW big data stochastic good for 4 webset
import numpy as np
import pandas as pd

def dynamic_matrix(N,Input_N_array):
    matrix_NbyN=[]
    #mm=[i for i in range(1,16+1)]
    for i in range(0,N*N,N):
        matrix_NbyN.append(Input_N_array[i:i+N])
        #print(i,i+n)
    return matrix_NbyN


def general_matrix_hub(name_of_web):
    bb=[]
    for i in name_of_web:
        for j in name_of_web:
            bb.append(i+j)
    return bb

def general_matrix_authority(name_of_web):
    bb=[]
    for i in name_of_web:
        for j in name_of_web:
            bb.append(j+i)
    return bb


def matrix_hub(link_A,n):
    hub=general_matrix_hub(name_of_web)
    matrix_size=n*n
    mm=[]
    for x in hub:
        if x in link_A:
            a=1
        else:
            a=0
        mm.append(a)
        #matrix=np.array([mm[0:3],mm[3:6],mm[6:9]])
        Input_N_array=mm
        matrix=dynamic_matrix(n,Input_N_array)
        
    return matrix


def general_matrix_hb_stoch(name_of_web):
    bb=[]
    for i in name_of_web:
        for j in name_of_web:
            bb.append(j+i)
    return bb

def matrix_hb_stoch(link_A,n):
    hub=general_matrix_hb_stoch(name_of_web)
    matrix_size=n*n
    mm=[]
    for x in hub:
        if x in link_A:
            a=1
        else:
            a=0
        mm.append(a)
        #matrix=np.array([mm[0:3],mm[3:6],mm[6:9]])
        Input_N_array=mm
        matrix=dynamic_matrix(n,Input_N_array)
        
    return matrix




def rec_multi(MM,hub_normized):
    hub_non_normized_new=np.matmul(MM,hub_normized)
    hub_normized_new=hub_non_normized_new*(sum(hub_normized))/sum(hub_non_normized_new)
    return [hub_non_normized_new,hub_normized_new]


def Rank_web(MM_martrix):
    vec_normalized=np.array([[1],[1],[1],[1]])
    vec_non_normized=np.array([[1],[1],[1],[1]])
    count_iter=1
    error0, error1, error2, error3=[1,1,1,1]
    while  (abs(error0) or abs(error1) or abs(error2) or abs(error3)) > 0.002:
        [vec_non_normized_new,vec_normalized_new]=rec_multi(MM_martrix,vec_normalized)
        #print([hub_non_normized_new,hub_non_normized_new])    
        error0 = vec_non_normized_new[0]-vec_non_normized[0]
        error1 = vec_non_normized_new[1]-vec_non_normized[1]
        error2 = vec_non_normized_new[2]-vec_non_normized[2]
        error3 = vec_non_normized_new[3]-vec_non_normized[3]
        vec_normalized=vec_normalized_new  
        vec_non_normized=vec_non_normized_new
        count_iter +=1
    return [count_iter,vec_non_normized,vec_normalized]


def rec_multi_stoch(MM,hub_normized):
    hub_non_normized_new=np.matmul(MM,hub_normized)
    hub_normized_new=hub_non_normized_new*(sum(hub_normized))/sum(hub_non_normized_new)
    return [hub_non_normized_new,hub_normized_new]



def Rank_web_Stochastic(M_martrix_stoch):
    vec_stoch=np.array([[1],[1],[1],[1]])
    
    count_iter=1
    error0, error1, error2,error3=[1,1,1,1]
    while  (abs(error0) or abs(error1) or abs(error2) or abs(error3)) > 0.002:
          
        vec_stoch_new=np.matmul(M_martrix_stoch,vec_stoch)
 
        error0 = vec_stoch_new[0]-vec_stoch[0]
        error1 = vec_stoch_new[1]-vec_stoch[1]
        error2 = vec_stoch_new[2]-vec_stoch[2]
        error3 = vec_stoch_new[3]-vec_stoch[3]
        vec_stoch=vec_stoch_new  
        count_iter +=1
    return [count_iter,vec_stoch]


def Rank_web_Stochastic_weight(M_martrix_stoch,K,C):
    vec_stoch=np.array([[1],[1],[1],[1]])
    
    count_iter=1
    error0, error1, error2,error3=[1,1,1,1]
    while  (abs(error0) or abs(error1) or abs(error2)or abs(error3)) > 0.002:
          
        vec_stoch_new=K*np.matmul(M_martrix_stoch,vec_stoch)+C
 
        error0 = vec_stoch_new[0]-vec_stoch[0]
        error1 = vec_stoch_new[1]-vec_stoch[1]
        error2 = vec_stoch_new[2]-vec_stoch[2]
        error3 = vec_stoch_new[3]-vec_stoch[3]
        vec_stoch=vec_stoch_new  
        count_iter +=1
    return [count_iter,vec_stoch]



name_of_web=['A','B','C','D']
link_hub_A=['AB','AC','BC','CA','DC']

#name_of_web=['N','M','A']
#link_hub_A=['NN','NA','AN','AM','MA']                             
                               
                               
#print(general_matrix_hub(name_of_web))

hub_martrix_= matrix_hub(link_hub_A,len(name_of_web))
#print(hub_martrix_)

hub_martrix=np.array(hub_martrix_)
aut_martrix=hub_martrix.T

M_Matrix=hub_martrix

hub_MMT_martrix=np.matmul(M_Matrix,M_Matrix.T)
aut_MTM_martrix=np.matmul(M_Matrix.T,M_Matrix)




print('Hub Martix = \n', hub_martrix)
print(' ')  
Hub_vec_Rank = Rank_web(hub_MMT_martrix)
print('Hub Rank Number of Converagnce Iteration = ',Hub_vec_Rank[0])
#print('Hub non-normalized vector = \n',Hub_vec_Rank[1])
#print('Hub normalized vector = \n',Hub_vec_Rank[2])
df_hub = pd.DataFrame(data=Hub_vec_Rank[1],  columns=['Hub Rank'], index=np.array(name_of_web).T)
display(df_hub)
key_=[name_of_web]
#valu_=list(dic.values())
#matrix=np.array(valu_)
print('-----------------------------------')    
print(' ')    

aut_Martix__=hub_martrix.T
print('Authority Martix = \n', aut_Martix__)
print(' ')  
Aut_vec_Rank = Rank_web(aut_MTM_martrix)
print('Authority Rank Number of Converagnce Iteration = ', Aut_vec_Rank[0])
#print('Authority non-normalized vector = \n',Aut_vec_Rank[1])
#print('Authority normalized vector = \n',Aut_vec_Rank[2])
df_aut = pd.DataFrame(data=Aut_vec_Rank[1],  columns=['Authority Rank'], index=np.array(name_of_web).T)
display(df_aut)
print('-----------------------------------')    
print(' ')  


print('Rank based on Stochastic Matrix')  
martrix_stoch_= matrix_hb_stoch(link_hub_A,len(name_of_web))
martrix_stoch=np.array(martrix_stoch_)
martrix_stochastic=martrix_stoch/martrix_stoch.sum(axis=0)
print(martrix_stochastic)
print('   ')


#martrix_stoch_= matrix_hb_stoch(link_hub_A,len(name_of_web))
#martrix_stoch=np.array(martrix_stoch_)
#martrix_stochastic=martrix_stoch/martrix_stoch.sum(axis=0)
#print(martrix_stochastic)




Stochastic_vec_Rank = Rank_web_Stochastic(martrix_stochastic)
print('Stochastic Rank Number of Converagnce Iteration = ', Stochastic_vec_Rank[0])
df_stoch = pd.DataFrame(data=Stochastic_vec_Rank[1],  columns=['Stochastic Rank'], index=np.array(name_of_web).T)
display(df_stoch)
print('-----------------------------------')    
print(' ') 


Stochastic_vec_Rank_weight = Rank_web_Stochastic_weight(martrix_stochastic,0.8,[[0.2],[0.2],[0.2],[0.2]])
print('Stochastic Rank based on weighted Matrix of 0.8*M+C')
print('Stochastic weight Rank Number of Converagnce Iteration = ', Stochastic_vec_Rank_weight[0])
df_stoch_weight = pd.DataFrame(data=Stochastic_vec_Rank_weight[1],  columns=['Stochastic Rank weight'], index=np.array(name_of_web).T)
display(df_stoch_weight)


Hub Martix = 
 [[0 1 1 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 1 0]]
 
Hub Rank Number of Converagnce Iteration =  9


Hub Rank
A  5.656494
B  3.999746
C  0.000254
D  3.999746

-----------------------------------
 
Authority Martix = 
 [[0 0 1 0]
 [1 0 0 0]
 [1 1 0 1]
 [0 0 0 0]]
 
Authority Rank Number of Converagnce Iteration =  9


Authority Rank
A        0.000433
B        3.999567
C        9.655800
D        0.000000

-----------------------------------
 
Rank based on Stochastic Matrix
[[0.  0.  1.  0. ]
 [0.5 0.  0.  0. ]
 [0.5 1.  0.  1. ]
 [0.  0.  0.  0. ]]
   
Stochastic Rank Number of Converagnce Iteration =  22


Stochastic Rank
A         1.600586
B         0.800293
C         1.599121
D         0.000000

-----------------------------------
 
Stochastic Rank based on weighted Matrix of 0.8*M+C
Stochastic weight Rank Number of Converagnce Iteration =  14


Stochastic Rank weight
A                1.453316
B                0.781327
C                1.565357
D                0.200000